name: project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  http: ^1.1.0
  shimmer_animation: ^2.1.0+1
  webview_flutter: ^4.4.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/aset/images/
    - lib/aset/icons/
  uses-material-design: true
